### ISSUE TITLE
missing advertised methods (e.g. Remove)

### ISSUE THREAD

**Issue by DickBaker** [Jeff-Klein/String.Extensions#3]
The page at https://github.com/Jeff-Klein/String.Extensions (README.md) claims several Remove* methods already exist but they don't. Are you going to implement or remove (pun intended!) from the docs ?

BTW that same page has typo "avaliable", and the first 2 methods start with "String." (inconsistent as the rest don't).

Could you please consider merging with StringExtensions project as you both cover very similar ground ? Thanks.

**Comment by Jeff-Klein** [comment]
Hi there.

Thanks for the tip about the readme file. I fixed it.
About the remove method through, I'm not sure what you mean. Could you be more specific?
The Remove class is right here:
https://github.com/Jeff-Klein/String.Extensions/blob/master/String.Extensions/src/Remover.cs

**Comment by DickBaker** [comment]
Jeff, Hi
Apologies indeed as the source does seem to be there. I can only guess that I was confused between your String.Extensions and Koen's StringExtension (as I cleared down all the browser windows I had open previously). Hopefully you will forgive me and review the scope of each to see if possible to combine into single [superset] package. Please close the Issue if I don't do so by clicking the right button ! 
rgds
Dick
